/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelasutama;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class futama extends javax.swing.JFrame {

    /**
     * Creates new form futama
     */
    public futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnama = new javax.swing.JLabel();
        btntkn = new javax.swing.JButton();
        btntknnim = new javax.swing.JButton();
        labelkelas = new javax.swing.JLabel();
        btntknkls = new javax.swing.JButton();
        labelnim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelnama.setText(" Nama ");

        btntkn.setText("Tekan Saya");
        btntkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntknMouseClicked(evt);
            }
        });
        btntkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntknActionPerformed(evt);
            }
        });

        btntknnim.setText("Tekan Saya");
        btntknnim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntknnimMouseClicked(evt);
            }
        });

        labelkelas.setText("Kelas");

        btntknkls.setText("Tekan Saya");
        btntknkls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntknklsMouseClicked(evt);
            }
        });

        labelnim.setText("Nim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntkn)
                            .addComponent(btntknnim)
                            .addComponent(btntknkls)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(labelnama))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(labelnim))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(labelkelas)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelnim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntknnim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntkn)
                .addGap(16, 16, 16)
                .addComponent(labelkelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntknkls)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntknMouseClicked
        // TODO add your handling code here:
        labelnama.setText("Nama: Andika Rahma Fauziah");
        JOptionPane.showMessageDialog(null, "Selamat anda berhasil mengubah label nama");
    }//GEN-LAST:event_btntknMouseClicked

    private void btntknklsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntknklsMouseClicked
        // TODO add your handling code here:
        labelkelas.setText("Kelas : IF-9");
        JOptionPane.showMessageDialog(null, "Selamat anda berhasil mengubah label kelas");
    }//GEN-LAST:event_btntknklsMouseClicked

    private void btntknnimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntknnimMouseClicked
        // TODO add your handling code here:
        labelnim.setText("Nim : 10118364");
        JOptionPane.showMessageDialog(null, "Selamat anda berhasil mengubah label nim");
    }//GEN-LAST:event_btntknnimMouseClicked

    private void btntknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntknActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntknActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new futama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntkn;
    private javax.swing.JButton btntknkls;
    private javax.swing.JButton btntknnim;
    private javax.swing.JLabel labelkelas;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnim;
    // End of variables declaration//GEN-END:variables
}
